### ISSUE TITLE
NPM install fails at gyp rebuild

### ISSUE THREAD

**Issue by OneMansGlory** [chalda/DiscordBot#10]
Not the best with programming, but doing npm install for the bot never works, and fails at gyp rebuild.

**Comment by chalda** [comment]
Hi,
Can you copy paste or screenshot the error message you are seeing?
Make sure you have node 0.12 installed NOT the latest 4.0
Also see if following the tips in this thread will help:
http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm
you might need to install python :(

**Comment by Einarin** [comment]
If you're building on Windows make sure you run from a visual studio command prompt too, or it won't be able to find the compiler. If you post the specific error we can help you try and troubleshoot.

**Comment by chalda** [comment]
I think I clicked to add visual Studio to path when I installed it or
something cause I've never had to run the bot with a special Vs shell.
Johnny let's figure out what node needs from vs and may be bundle it with
the repo. I doubt we can make a node "installer" but may be a startup
script like pull and deploy.

**Comment by OneMansGlory** [comment]
Worked! Thanks, but im still getting the hang of it.
