### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by nam192** [chalda/DiscordBot#12]
i keep getting this error 
http://imgur.com/nS7olnw

**Comment by chalda** [comment]
Hi, seems like a problem with your auth.json. make sure its properly formatted. You are either missing a quote or have an extra comma. Every quote must be closed. make sure you dont have a trailing comma. (ie on the last line of the auth json right before the close `}` )
{ "thing":"thing",
"thing2": "otherthing"
}

**Comment by nam192** [comment]
okay i seem to have have fixed it.but what is it supposed to say when its working ?

**Comment by chalda** [comment]
umm something along the lines of "Listening in x channels" If you havent joined a server with your bot account it might not say anything at all.. (tbh i dont remember)
Ok so,
go to the webapp (discordapp.com or somesuch) and log in as your bot (or use an invite link heh!) join all the channels that you want him to listen in.

**Comment by OneMansGlory** [comment]
It says "Ready to begin! Listning on __ channels!"

**Comment by chalda** [comment]
-- todo add a json file with channels to listen on.

been busy, need to give discordbot some love.

**Comment by nam192** [comment]
so now when i run it.It just says Disconnected!

**Comment by OneMansGlory** [comment]
auth.json is probs set up wrong. Double check that.

**Comment by nam192** [comment]
Double checked it,made new auth.jason same result, tried to login via the desktop app nothing new

**Comment by OneMansGlory** [comment]
Do you have the proper version of node.js? That was giving me trouble. You need 0.12.xx.
I'm no genius here so...

**Comment by kirby561** [comment]
@nam192 Not sure if that was just a typo but it should be "auth.json", not "auth.jason"

**Comment by nam192** [comment]
i have the proper version of node.js. and my it was just a typo. i am still getting Disconnected!

**Comment by chalda** [comment]
Double check credentials. It's not something with the bot. Either username
or password are incorrect

**Comment by Wokkels** [comment]
I keep getting the :339 error, no idea where it goes wrong http://imgur.com/QZuHRxY

**Comment by Einarin** [comment]
It can't find the wolfram plugin, which we use for !wolfram. Have you run npm install/npm update?

**Comment by Einarin** [comment]
These days the bot should be able to handle the wolfram plugin being missing. I added checking code to handle when it's not present. @Wokkels did you get it working?

**Comment by Einarin** [comment]
I rewrote the wolfram command. It doesn't depend on libxmljs any more.
