### ISSUE TITLE
win npm spawn issue pullanddeploy solved

### ISSUE THREAD

**Issue by BannukDE** [chalda/DiscordBot#121]
https://github.com/chalda/DiscordBot/blob/abf5253835faf50e316a0fbf2a0eeae8cddfea8b/plugins/Dev/dev.js#L30

Someone still working on this?

Here a little bugFix:
var npm = spawn(/^win/.test(process.platform) ? 'npm.cmd' : 'npm', ['install']);

Checks for plattform win and fixes alltime bug.

**Comment by sr229** [comment]
@BannukDE you're better off makign a pull request to fix this

**Comment by F9Alejandro** [comment]
Been stale for 3 years going to close.
