### ISSUE TITLE
How I Fix Perms?

### ISSUE THREAD

**Issue by ZTzTopia** [chalda/DiscordBot#125]
When I Do !eval My Bot Say You are not allowed to run eval! How I Fix It?

**Comment by Kyrisx** [comment]
You have to modify permissions.json. If you set the eval permission to true globally, everyone can use it. Otherwise, add it for a specific user under "users".

**Comment by Einarin** [comment]
Per guild permissions could definitely be useful. I started with global ones because I wanted to add commands that had to be locked down, and then was just adding myself as the bot owner. It would be good to be able to give admins/mods powers on specific guilds though!

**Comment by F9Alejandro** [comment]
it will basically replace the cmdauth or it can stay in place and this is just an extension being in Admin. In order for this to work I had to do a fair bit of changes to be sure it will read from the correct places. There is still a fair bit that I need to change before I make a pull request. (Note this will have per guid/user/role management.)

**Comment by geekysonic** [comment]
> You have to modify permissions.json. If you set the eval permission to true globally, everyone can use it. Otherwise, add it for a specific user under "users".

how can i set it to only be used by certain users, how do i access it?

**Comment by geekysonic** [comment]
> > You have to modify permissions.json. If you set the eval permission to true globally, everyone can use it. Otherwise, add it for a specific user under "users".
>

**Comment by geekysonic** [comment]
how do i access it?

**Comment by geekysonic** [comment]
also, can you guys help me with my brand new discord bot too please?

**Comment by F9Alejandro** [comment]
closed due to stale report.
