### ISSUE TITLE
Can't find module 'wolfram'

### ISSUE THREAD

**Issue by MrBlackadder** [chalda/DiscordBot#13]
https://i.gyazo.com/53ed7dbea2f652ca70538930aae19ab0.png

Whenever I try running node discord_bot.js this shows up

**Comment by Einarin** [comment]
Wolfram is a node package we use. Have you run `npm update`?

**Comment by MrBlackadder** [comment]
Thanks for the reply, I will try it out

**Comment by Einarin** [comment]
Due to continuing problems with the wolfram plugin, I added error handling to continue without the !wolfram command if wolfram.js isn't cooperating. 8c6672c3137e053396f55ac756fc57d4a4b8b987
Closing this for now, let us know if you're still having issues.
