### ISSUE TITLE
i am on cromebook

### ISSUE THREAD

**Issue by RuchPlayzYT** [chalda/DiscordBot#136]
ok so i am on cromebook so i can not download any windows things

**Comment by ItsLachy** [comment]
You should put your chromebook in developed mode and the you should be able to run software on it.

**Comment by F9Alejandro** [comment]
https://medium.com/@jacoboakley/web-development-with-a-chromebook-terminal-setup-dc0d4668d411 and https://medium.com/@jacoboakley/web-development-with-a-chromebook-installing-nodejs-4e358b82a31b should help you greatly with chromebook development

**Comment by Einarin** [comment]
Closing as this isn't an issue with the bot.
