### ISSUE TITLE
Youtube search broken

### ISSUE THREAD

**Issue by kellerinstitute** [chalda/DiscordBot#155]
Using !youtube only returns `"Syntax: !youtube <video tags>"` The youtube api key is set and image search works properly. I'm on nodejs 14.4.0

**Comment by Einarin** [comment]
I changed it to provide better errors when there's a problem

**Comment by chalda** [comment]
@kellerinstitute please pull latest master @Einarin did a TON of work in july to fix a lot of the issues around youtube
