### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by GamingGamers** [chalda/DiscordBot#159]
How to create template

**Comment by F9Alejandro** [comment]
What do you mean by "template"?

**Comment by GamingGamers** [comment]
> What do you mean by "template"? Do you mean the config file?

No, i medan hos to create a template File and shared in YouTube server!

**Comment by F9Alejandro** [comment]
there are many files that are considered templates, please expand on what your mean.

**Comment by F9Alejandro** [comment]
Closing after no response from OA after 3+ months.
