### ISSUE TITLE
Play command fails on search/Youtube URLs

### ISSUE THREAD

**Issue by Einarin** [chalda/DiscordBot#167]
The play command uses youtube-dl, which has received a [DMCA takedown by the RIAA](https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md). Presumably this is the reason Youtube is broken. Soundcloud URLs have been tested to still work.

**Comment by chalda** [comment]
might want to consider spotify integration 🤔 alternatively ive already seen a few unofficial forks of youtube-dl that are being maintained.

**Comment by Einarin** [comment]
There was an official update to youtube-dl, so it's working again for now. How would spotify integration work? [The only bot I've seen support that actually uses youtube for the audio, see their help article.](https://groovy.zendesk.com/hc/en-us/articles/360030600932-How-Groovy-plays-music-from-Spotify-and-Apple-Music-Deezer-)

**Comment by Einarin** [comment]
Support for spotify links and playlists and such would be super cool and is definitely doable

**Comment by F9Alejandro** [comment]
Just be careful as we don't want spotify breathing down our necks, plus discord already has spotify integration.

**Comment by Einarin** [comment]
The main problem here seems to have been resolved with the restoration of youtube-dl. Closing because hopefully there's nothing we need to do.
