### ISSUE TITLE
Bot Upgrade & Music Player

### ISSUE THREAD

**Issue by botea14** [chalda/DiscordBot#170]
Hi,

I'm using your code, with some changes, and the bot is already up and running and accepted by TOP.GG.

https://top.gg/bot/737792016435511296 - check details here.

Transformed it into keyword interactive GIF response when bot reads specified keywords in chat ( around 100 keywords with multiple gifs )

A little customization on command response appearances and a few small improvements.

I'll be happy to share modified codes with you if you find it interesting.

I have some issues while using music player ...

```
Error: Command failed with exit code 127: /home/container/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -i --max-downloads 1 --no-playlist --no-check-certificate -- ytsearch1:test
    at makeError (/home/container/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/home/container/node_modules/execa/index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  command: '/home/container/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -i --max-downloads 1 --no-playlist --no-check-certificate -- ytsearch1:test',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "/usr/bin/env: 'python': No such file or directory",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Maybe you are able to solve this issue :( 

Thanks,
Alex.

**Comment by F9Alejandro** [comment]
you are either missing python or youtube-dl
