### ISSUE TITLE
run on centos - fail npm install

### ISSUE THREAD

**Issue by botea14** [chalda/DiscordBot#172]
I was trying to run bot from CentOS 8 Machine x64.

I get following error when do `npm install`
![npminstall](https://user-images.githubusercontent.com/37483645/98465334-1b9baa00-21d1-11eb-8a82-4637d491e17e.PNG)

I had to replace packages and packages-lock with some old versions and then run `npm install` and `npm install memorystream`

All works good now. 

I have created an install tutorial for CentOS8 but works only with old versions of packages and packages-json.

If you can solve the issue to work with new packages and packages-json i can share the tutorial to be added on bot readme file.

Thanks,
Alex.

**Comment by chalda** [comment]
can you report the version of npm and node you are using on that centos machine? it might be our lockfile is outdated?

**Comment by F9Alejandro** [comment]
I was using node v12 lts instead of 15 or 14 as some packages break with the newer versions of node. try something called nvm it is able to grab different node versions and change between them depending on the project via nvm install v(some node version).

**Comment by botea14** [comment]
npm version 6.14.8
node version 12.19.0

**Comment by F9Alejandro** [comment]
deleting the package-lock.json should allow you to do npm install it just won't read from the lock file, it could be that it was malformed when you got a copy of the git repo.

**Comment by F9Alejandro** [comment]
Stale issue. Closing.
