### ISSUE TITLE
Crash due to trying to send a message to someone we cannot

### ISSUE THREAD

**Issue by Einarin** [chalda/DiscordBot#174]
```
treating ?help from 680686691937288234 as command
DiscordAPIError: Cannot send messages to this user
    at RequestHandler.execute (D:\Projects\DiscordBotWindows\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  name: 'DiscordAPIError',
  message: 'Cannot send messages to this user',
  method: 'post',
  path: '/channels/781412747908218900/messages',
  code: 50007,
  httpStatus: 403
}
```

**Comment by F9Alejandro** [comment]
maybe a try catch to see if the message can be sent to their DM if not send a message in the channel the message was sent from to let the user know that they need to allow DM on the server for the bot to message them.

**Comment by MahmoudHendi1** [comment]
I agree with @F9Alejandro, I can do it if you want.

**Comment by warmpigman** [comment]
Well, you can just disable the exit on error, which is a bad idea imo, have it check if it can dm, then dm otherwise return

**Comment by Uklizdev** [comment]
Discord js api does not let you check if you can or not send the message. The only way to know is actually sending it. so what you gotta do is catch every time you wanna send a dm so bot won't crash

**Comment by chalda** [comment]
Makes sense to me. Sorry I've been away not really putting in fixes. Lifes
been very hectic recently. I'll try to get to this next week

**Comment by F9Alejandro** [comment]
I can do a quick fix and make a pull request for testing.

**Comment by chalda** [comment]
Testing badpokerface.png what's that?

**Comment by F9Alejandro** [comment]
Dunno what you are talking about. You may want to go on github site to view the actually issue ticket
