### ISSUE TITLE
sometime an error message

### ISSUE THREAD

**Issue by caniplay** [chalda/DiscordBot#175]
Ssdd

**Comment by F9Alejandro** [comment]
Can you please expand on what "Ssdd" means?

**Comment by chalda** [comment]
Thank you for your contribution to the development of this discord bot

**Comment by F9Alejandro** [comment]
again can you please explain more on what you mean, just saying that there is sometimes an error message does nothing for supporting you.

**Comment by F9Alejandro** [comment]
Lack of information and no response after 23 days of inactivity
