### ISSUE TITLE
Command Handler When?

### ISSUE THREAD

**Issue by Dragonizedpizza** [chalda/DiscordBot#176]

**Comment by chalda** [comment]
please elaborate on what you mean by command handler?
the bot already handles plenty of commands

**Comment by Dragonizedpizza** [comment]
A command handler is a way you can give each command a single file.

https://anidiots.guide/first-bot/a-basic-command-handler#:~:text=A%20Command%20Handler%20is%20essentially,you're%20being%20fancy
).

**Comment by F9Alejandro** [comment]
bot already has a built in command handler, please look at the other commands under the folder plugins.

**Comment by chalda** [comment]
as @F9Alejandro said, the bot is already basically configured this way. take a look at 
https://github.com/chalda/DiscordBot/blob/master/discord_bot.js#L98

it might not be as fancy as the one you linked but its basically the same idea. the plugins folder has code for specific commands that are more than 1-2 lines of code.  if you want to extend it to do something you want, you can add your command to the switch statement.

its may be a good idea to organize the way that tutorial does but seems like a lot of work for some of the commands which have very little code

**Comment by Dragonizedpizza** [comment]
Alrighty.
