### ISSUE TITLE
Clarify steps for Custom Search.

### ISSUE THREAD

**Issue by SchwererKonigstiger** [chalda/DiscordBot#19]
Clarify the steps for CS setup on the google developer's webpage. Perhaps add to readme.md when correctly formatted in markdown. I had to figure out that I needed only the search engine ID code rather than its actual full URL for the Bot. The webpage at stackoverflow is slightly unclear on it.

Create a Custom Search at:
https://cse.google.com/cse/create/new
Leave the first line blank, and name the search engine anything you wish.
Click "Advanced Options" and then type ImageObject.
Hit create.
On this new page, enable the Image Search in the menu.
Then press "Search engine ID" under the Details header.
Copy this into the auth.json's "google_custom_search" section.

Make sure you also have your google server API key, which goes in the "youtube_api_key" section, or the search will fail.

**Comment by chalda** [comment]
ok yeah, so I also was confused about the whole "URL" section of the search engine. Thanks for this. honestly i dont understand why google makes their dev tools so convoluted to use.

**Comment by chalda** [comment]
I am gonna add this to the main page wiki

**Comment by SchwererKonigstiger** [comment]
It makes it "Fun"
Closing issue.
