### ISSUE TITLE
Unfinished Rename

### ISSUE THREAD

**Issue by abalabahaha** [chalda/DiscordBot#20]
https://github.com/chalda/DiscordBot/blob/master/plugins/Moderation/moderation.js#L23

It appears someone started to rename some variables and forgot to finish. Testing code before upload would help :|

**Comment by chalda** [comment]
uhoh @Einarin ?

in the mean time feel free to write some unit tests ;) @abalabahaha

**Comment by Einarin** [comment]
hmm, I should have disabled ban and unban before pushing as I haven't gotten a ban to actually work yet. Surprised I didn't hit this when I was testing.

**Comment by Einarin** [comment]
I keep not getting to this. I'm disabling these since we shouldn't have broken commands available. dfbffdba86a5680b77226de3002020c804d319b1
