### ISSUE TITLE
!help causing bot to disconnect/stop working.

### ISSUE THREAD

**Issue by Darkvapour** [chalda/DiscordBot#22]
Hi,
Every-time I type !help, the bot crashes, disconnects from Discord and shows an error in my terminal window.
Others commands seem to work ok and the bot sends messages in the channel ok. 
Only !help does not work.

Here is what I get:
http://pastebin.com/Jv7HYag0

Node v0.12.7 on Ubuntu-14.04.1 64-Bit.

**Comment by Einarin** [comment]
`!help` is special in that it PM's you instead of responding. It used to just respond but there are so many commands that it was causing channel flooding so I changed it. That's probably why only it is affected.

First off, can you try running `npm update`? Since the stack trace is from discord.js, I want to check that you're on the latest version, which is 5.2.0 as of this moment. You can check your discord.js version with `npm ls discord.js`

**Comment by Darkvapour** [comment]
Ok, I ran `npm update` in the DiscordBot directory, looks like it did some compiling or something, looks like there are no problems there.
Then I did `npm ls discord.js`, which returned: `discord.js@5.2.0` - looks like the latest version.
Still seems to break on `!help`.

**Comment by OBenned** [comment]
I have the same problem, also on the latest version of the bot

**Comment by Darkvapour** [comment]
I've managed to get `!help` to work now.
Turns out the node version I was on was the problem.

So now I use the V5.X branch from the node GitHub, compiled & installed from the source and now everything works great.
The only problem I had left was just with node, as it wouldn't let me use npm install.
However that problem was soon solved after I found this:
http://stackoverflow.com/questions/12947145/error-pre-versions-of-node-cannot-be-installed-use-the-nodedir-flag-instea

From that page I used the command below and it installed/compiled with no problems. 
`npm install --nodedir=/home/userarea/node`

**Comment by OBenned** [comment]
@Darkvapour Nice man! great info, i will try it when i get home

**Comment by leonteale** [comment]
did this work for you then? as i haev the same problem with !help. in that i get no response from it whatsoever, but the console does see the !help command come through, but i see nothing in the public feed or in a PM. i am using node V4.x also.

**Comment by Einarin** [comment]
This got changed as part of the Discord.js 9 update. should be all good now.
