### ISSUE TITLE
how do I join a server with the bot?

### ISSUE THREAD

**Issue by Sonnyluu** [chalda/DiscordBot#28]
Hi

so I basicly got this in my cmd:
http://puu.sh/m7fHp/99c5f5f20a.png

But I have no idea how I make the bot join my server..

**Comment by Einarin** [comment]
For anyone else wondering this the bot will start in whatever servers you already connected the account to. Then you can use !join to give the bot additional servers to join.

**Comment by chalda** [comment]
ok we need to provide the config with an init url and use it to join
(somehow) the server its the invite to if after login we detect that the
bot has 0 channels. i bet the invite link is like a base64 encoding of the
server name or something. Does discord.js have any support for joining a
server from link or name?

On Thu, Dec 24, 2015 at 12:31 PM, Johnny Dickinson <notifications@github.com

**Comment by Einarin** [comment]
The bot already supports joining servers from a discord invite using `!join-server`. I don't think it's a big deal to have to get a way to communicate with the account given you have to create it manually initially anyway.
