### ISSUE TITLE
admin lists

### ISSUE THREAD

**Issue by chalda** [chalda/DiscordBot#3]
restrict who can !pullanddeploy

**Comment by Einarin** [comment]
I wonder if this would be a fix for a !cmd command. I want to add one that lets users run javascript, but node doesn't seem to have a real sandbox. Maybe arbitrary javascript is ok if you trust the user...

**Comment by Einarin** [comment]
Btw I created support for admin permissions in 293603300a4537ce3007610a8c417706c303e386. It doesn't restrict !pullanddeploy yet though, just !eval.

**Comment by Einarin** [comment]
#64 was this same idea again. Should be pretty simple to do

**Comment by Einarin** [comment]
Implemented in f6b9b31f2e1742d0992f86a0c5452906b81734
