### ISSUE TITLE
YouTube search returns link with "undefined"

### ISSUE THREAD

**Issue by Doofcake** [chalda/DiscordBot#35]
As the title suggests, the youtube search seems to work fine, but when outputting the link, it just outputs http://www.youtube.com/watch?v=undefined

EDIT: Just noticed that it actually does work okay most of the time, but the "undefined" seems to occur when the search terms aren't specific enough? I'm not sure, this is strange.

**Comment by SteamingMutt** [comment]
This is because the first result from the search is most likely a channel, and since that isn't a video, it'll print undefined.

**Comment by milesflo** [comment]
The search query returns undefined if nothing is found on YouTube's end. That's just how the API works. If you want if to return a "Not Found" message when that happens, you can write an if statement to handle that.

**Comment by milesflo** [comment]
EDIT: This has been patched! Pull from master to get the fix.
