### ISSUE TITLE
Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by R3ido101** [chalda/DiscordBot#36]
npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.
[npm-debug.log.txt](https://github.com/chalda/DiscordBot/files/99961/npm-debug.log.txt)

**Comment by frostshoxx** [comment]
I had the same problem on Windows, I ended up having to install the C++ compiler/component in Visual Studio 2015 first.

**Comment by R3ido101** [comment]
ahh ok
