### ISSUE TITLE
Failed at node-opus node-gyp rebuild

### ISSUE THREAD

**Issue by crater0** [chalda/DiscordBot#37]
Not sure what I'm doing wrong. While trying to install DiscordBot (or node-opus manually) causes errors and this error file.
[npm-debug.txt](https://github.com/chalda/DiscordBot/files/107177/npm-debug.txt)
The following error occurs for almost every project being built.

`..\..\deps\opus\src\opus_encoder.c(29): fatal error C1083: Cannot open include file: 'config.h': No such file or directory [C:\Users\Matthew\Documents\DiscordBot\DiscordBot-master\node_modules\node-opus\build\deps\libopus.vcxproj]`
`..\..\deps\opus\src\opus.c(29): fatal error C1083: Cannot open include file: 'config.h': No such file or directory [C:\Users\Matthew\Documents\DiscordBot\DiscordBot-master\node_modules\node-opus\build\deps\libopus.vcxproj]`
`..\..\deps\opus\src\opus_multistream.c(29): fatal error C1083: Cannot open include file: 'config.h': No such file or directory [C:\Users\Matthew\Documents\DiscordBot\DiscordBot-master\node_modules\node-opus\build\deps\libopus.vcxproj]`
`..\..\deps\opus\src\opus_decoder.c(29): fatal error C1083: Cannot open include file: 'config.h': No such file or directory [C:\Users\Matthew\Documents\DiscordBot\DiscordBot-master\node_modules\node-opus\build\deps\libopus.vcxproj]`

And this error occurs after attempting to build the solution.

`gyp ERR! build error`
`gyp ERR! stack Error: 'C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe' failed with exit code: 1`
`gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)`
`gyp ERR! stack     at emitTwo (events.js:87:13)`
`gyp ERR! stack     at ChildProcess.emit (events.js:172:7)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)`
`gyp ERR! System Windows_NT 10.0.10586`
`gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"`
`gyp ERR! cwd C:\Users\Matthew\Documents\DiscordBot\DiscordBot-master\node_modules\node-opus`
`gyp ERR! node -v v4.2.6`
`gyp ERR! node-gyp -v v3.0.3`
`gyp ERR! not ok`

Any help would be appreciated.

**Comment by Einarin** [comment]
The setup is failing trying to build node-opus, which discord.js uses for voice chat. I took a quick look at the node-opus bug tracker and saw [this](https://github.com/Rantanen/node-opus/issues/11), then noticed your node is in Program Files (x86).

It looks like you're running 32 bit node.js, and node-opus only supports 64 bit on Windows. Try switching to 64 bit node, I suspect that will solve your problem.

**Comment by crater0** [comment]
Ah, that did it.

Thanks for the help!
