### ISSUE TITLE
Adding a custom command?

### ISSUE THREAD

**Issue by faiizow** [chalda/DiscordBot#38]
Something like !addcom !lol hehehe would be good.

**Comment by Sikksens** [comment]
have you tried !alias?

**Comment by faiizow** [comment]
!alias !test test
!alias !test2 !say test

both don't work.

**Comment by crater0** [comment]
!alias only works without "!"

so '!alias test say test' should work.

On Fri, Jan 29, 2016 at 9:51 AM, faiizow <notifications@github.com> wrote:

> !alias !test test
> !alias !test2 !say test
>
> both don't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chalda/DiscordBot/issues/38#issuecomment-176885319>.
>



-- 
Matthew Carter

**Comment by faiizow** [comment]
it doesn't work

**Comment by faiizow** [comment]
how do i remove the ! prefix?

**Comment by chalda** [comment]
Fuck I've been swamped with work recently but holy crap there is a lot of
people providing support . :D thanks guys
