### ISSUE TITLE
watch2gether feature

### ISSUE THREAD

**Issue by chalda** [chalda/DiscordBot#43]
a bunch of requests on reddit for this.

basically would !watch2gether <youtube.url>

they dont have an API but i can probably hack around that with some cURL :dancer: 

there are several competitors so can look into those as well.

**Comment by milesflo** [comment]
Please do! What a great feature to have!

**Comment by chalda** [comment]
just commited this. was really easy actually
https://github.com/chalda/DiscordBot/commit/34a95e76cba18cac573c79f9bc6b1fec4474b478
