### ISSUE TITLE
Keep getting "Please create an auth.json"

### ISSUE THREAD

**Issue by Nickmane** [chalda/DiscordBot#49]
http://pastebin.com/kRj3qf8f
My auth.json http://imgur.com/eI6RWGy (have since removed the youtube api key)
I have made the auth.json from a duplicate of the auth.json.example
Not sure what I'm doing wrong :S

**Comment by Einarin** [comment]
The bot is complaining that you have a stray " somewhere in your auth.json. What you posted looks correct as far as I can tell however. You'll have to double check that your file is valid json. If you need to there are tools you can use to check json files for validity.

**Comment by Nickmane** [comment]
:| it was a “ instead of a  " around the email address, autocorrect did it again. Sadly now I'm getting this http://pastebin.com/eHtWvEnL . Am I missing something? http://imgur.com/f9vhtc6

**Comment by Nickmane** [comment]
nvm, had it in the wrong folder. Thanks for your help :+1:
