### ISSUE TITLE
how to setup permissions.json?

### ISSUE THREAD

**Issue by skyleter** [chalda/DiscordBot#50]
i dont understand, sorry

**Comment by SteamingMutt** [comment]
Let's say your Discord ID is 1234 and you want to use eval and restrict it for everybody else.

```json
{
	"global":{
		"eval": false
	},
	"users":{
		"1234":{
			"eval": true
		}
	}
}
```
This will enable only you to use eval and nobody else.

**Comment by mogokcp** [comment]
thx :)

**Comment by mogokcp** [comment]
@《Şᗪ》💎 ŜKYŁẸŤẸŘ doesn't have permission to execute eval!
 
not worked :(

**Comment by SteamingMutt** [comment]
Are you sure you've entered an ID instead of an username?

You can get your id via !myid

**Comment by mogokcp** [comment]
i have this
```
{
	"global":{
		"eval": false
	},
	"Elite Member":{
		"145022418828656640":{
			"eval": true
		}
	}
}
```

ps do u know how to set a welcome message when a user join ? ...

**Comment by SteamingMutt** [comment]
You're not supposed to change `users` to something else (Elite Members)

I don't t know about welcoming

**Comment by mogokcp** [comment]
thanks.

And :(

**Comment by Sikksens** [comment]
you can use something like this as a welcome message.

`bot.on("serverNewMember", function(server, user){
	bot.sendMessage(server.defaultChannel, "Welcome" + user.username);
	})`

**Comment by chalda** [comment]
Nice thing about java script projects like this is anyone who has stringed
together a website can probably hack in whatever features they want. That
being said we should move this in as an actual plugin so that It can be
toggled on off

**Comment by mogokcp** [comment]
what line?

**Comment by chalda** [comment]
You could prolly drop that anywhere in the main js file tbh.

**Comment by mogokcp** [comment]
discord_bot.js ?
I put it : 

```

// WELCOME MSG
bot.on("serverNewMember", function(server, user){ bot.sendMessage(server.defaultChannel, "Welcome to SD Chat! " + user.username); })
```

at line 730 just after `//message isn't a command or is from us  ` code

How can i do it to when a user connect instead of newmember?

**Comment by nickfoon** [comment]
So if I am trying to make it so that everyone cannot use certain commands, would the format look like this?
`
{
    "global":{
        "eval": false,
        "idle": false,
        "delete" false
    },
    "users":{
        "136272020525547521":{
            "eval": false
        }
    }
}
`

**Comment by Nerdietony** [comment]
What does eval stand for?

**Comment by chalda** [comment]
@Nerdietony eval[ulate]. it can take a string, parse it as javascript and execute. Its not very safe as you could potentially do some nasty stuff like overwrite the program internals etc. dont think it actually lets you do it for our app, but when you have javascript in the browser you could definitely do that.

**Comment by Nerdietony** [comment]
Oh yeaah, thanks.
