### ISSUE TITLE
really want to have a hackathon to add voice/dj features + fix everything.

### ISSUE THREAD

**Issue by chalda** [chalda/DiscordBot#52]
So me and @Einarin are in MA. I am busy this weekend but I would probably be down to do some intense ChaldaBot work the weekend after! Anyone else local to New England? Otherwise you can may be join remotely over discord!

Speaking of which we should have an official DiscordBot discord channel. Or may be a room in the discord.js/discord dev room. ( I heard they are annoyed by all the people coming in for help with deployments haha)

**Comment by Devlix** [comment]
Yeah I could join and help out. I messed around with the voice stuff and actually made a plugin where you can listen to a twitch broadcaster and it works pretty well. I think there will be another deployment issue with that as it needs ffmpeg or avconv to play the audio so need to figure out how to download those with the bot. I think having a place on discord we could talk about development is a good idea to make communication easier.

**Comment by chalda** [comment]
I added a link directly to the server in the readme

**Comment by Devlix** [comment]
The link you gave does not to appear to be an actual invite link. There is a button next to the voice/chat channel names to create these links.

**Comment by Einarin** [comment]
Re deployment issues, discord.js already pulls in libopus, so to an extent we already have those deployment issues. What is twitch using for their audio codec? The deployment issues get more complicated if the codecs they use have patents.

**Comment by milesflo** [comment]
Still planning on going this weekend?
