### ISSUE TITLE
google-images@0.1.4 No repository field.

### ISSUE THREAD

**Issue by thegimliboy** [chalda/DiscordBot#55]
I can run npm install for the first time and it installs everything, but when I try to run discord_bot.js it outputs 
```
node discord_bot.js 
Please run npm install and ensure it passes with no errors!
```

So I run npm install again and it outputs this:
```
npm install
npm WARN package.json google-images@0.1.4 No repository field.
```

**Comment by xmx1024** [comment]
I had this issue before, update nodejs.

**Comment by chalda** [comment]
@xmx1024 what node are you currently using that works best? 4 or 5? At the time of starting the project I used 0.12 so thats what it says in the Readme. This should prolly be updated to w/e works currently.

**Comment by thegimliboy** [comment]
@xmx1024 It is up-to-date... I tried it on a frash ubuntu server and installed it right before trying this

**Comment by Einarin** [comment]
Closing due to age. Feel free to comment/reopen if needed.
