### ISSUE TITLE
Can't get image search working

### ISSUE THREAD

**Issue by shandrydan** [chalda/DiscordBot#61]
I've got the bot up and running, and I'm 90% sure I've done everything right regarding my google server API and custom search yet my !image commands yield no results.

If possible, could someone please provide a more detailed outline on how to get the image search function to work from scratch? 
I'm not too familiar with this sort of thing and I could use a little extra clarity on the matter.

Other than that, awesome bot! Everything else* works great.

 *[other than !help (doesn't cause me to crash though, so I haven't really bothered to troubleshoot it)]

**Comment by nmynarcik** [comment]
I had the same issue...I had to actually go into my Google Dev Account, select the Application I created for this. Add the Custom Search API to that account (from: https://console.developers.google.com/apis/library?project=<YOUR APP>&q=Custom). Then get a SEARCH ENGINE ID (from: https://cse.google.com/cse/setup/basic) and paste that into my auth file.

**Comment by chalda** [comment]
Yeah this is a very unfortunate part but no way around this. Had to do the
same to setup a hubot for hipchat at work. Google just made it very
difficult to plug and play a search engine into stuff. Their menus are
convoluted at best

**Comment by shandrydan** [comment]
>I had the same issue...I had to actually go into my Google Dev Account, select the Application I created for this. Add the Custom Search API to that account (from: https://console.developers.google.com/apis/library?project=&q=Custom). Then get a SEARCH ENGINE ID (from: https://cse.google.com/cse/setup/basic) and paste that into my auth file.

That's what I did too but it's still not working. In your auth did you put your CSE server API in the youtube_api_key line? Or should it be with my 

Also, my console gives me an error 'project marked for deletion' whenever I attempt an image search,
I can say with relative certainty it isn't.

I'm gonna look over everything, I made a stupid mistake at some point.

**Comment by shandrydan** [comment]
### I don't know what I did, but it's working now!
I'm not sure who's responsible for it being fixed, so I'm just thankful in general.

Thank you nmynarcik, you were my muse.

And thank you chalda for the rad bot!
