### ISSUE TITLE
Is it possible to only have the bot listen on specific channels of a server?

### ISSUE THREAD

**Issue by Burgy123123** [chalda/DiscordBot#63]
Title says it all.
I'm fairly new to Node.js and really only know basics, but can I set it so that the bot only listens to on Off Topic channel of a server instead of every channel for every server? Or will I have to make my own plugin for this?

**Comment by Burgy123123** [comment]
Anyone?

**Comment by chalda** [comment]
Hi,
create a user account for the bot and put him in the channels you want. he
will only sit in the channels that you join when you login as the bot.

**Comment by DerfOh** [comment]
We have the bot set up with a specific roll name. If we ever feel that a bot needs to be removed from the channel we take away read permission for his roll. 

I hope this helps.

**Comment by Burgy123123** [comment]
I didn't know there were channel specific permissions. That's super handy! Thanks!

**Comment by DerfOh** [comment]
No problem. Have fun!

**Comment by Einarin** [comment]
I think roles covers this adequately. Closing.
