### ISSUE TITLE
is there a way to lock down the requests to authors/roles

### ISSUE THREAD

**Issue by leonteale** [chalda/DiscordBot#64]
i would have asked this in your discord but your link to discord doesn't work. 

Is there a way to lock down all or some commands to specific user roles or users?

**Comment by DerfOh** [comment]
There is some of that in the permissions file from what I know.



On Thu, Apr 14, 2016 at 5:16 AM -0700, "Leon Teale" <notifications@github.com<mailto:notifications@github.com>> wrote:


i would have asked this in your discord but your link to discord doesn't work.

Is there a way to lock down all or some commands to specific user roles or users?

-

**Comment by Einarin** [comment]
I started the permissions file because the !eval command was too cool not to have, and far too dangerous to make available to everyone. Expanding it to other/all commands is a good idea!

**Comment by Einarin** [comment]
This should work now f6b9b31f2e1742d0992f86a0c5452906b81734a4. Any command can be allowed or denied globally or for individual users with permissions.json. by default eval and pullanddeploy are globally disabled because they're dangerous.
