### ISSUE TITLE
Yet another npm install issue

### ISSUE THREAD

**Issue by dr4chen** [chalda/DiscordBot#68]
Let me preface this issue by saying I virtually know nothing about any of the programming involved in all of this. I do however know how to follow instructions and run installers, and as far as I know I've done everything correctly, yet I'm still facing this issue. 

I'm certain you all are tired of receiving topics like this one, but even after reviewing all of the others Issues pertaining to this, as well as reviewing the links supplied beneath Installation, I can't get this damn thing to work.

The funny thing is, I seem to get different errors every time I uninstall and reinstall prerequisites. 

I will walk you all through my most recent attempt:

- Installed Python 2.7 (and selected the Add to Path option in installer)

- Installed Node.js (version 6.2.0)

- Installed Visual Studio Community 2015 [with these options selected](http://i.imgur.com/QUCHQ5a.png)

- [Followed most of the Windows 10 instructions here](http://i.imgur.com/LYtmhaB.png)

- Restarted my computer

And then I attempted to npm install within the DiscordBot directory. Instead of doing what it's supposed to, I received a volley of yellow colored errors followed by red colored errors, and then the infamous node-gyp or whatever the hell issue. Being curious, I tried to node discord_bot.js anyway and nothing seemed to work. 

I don't understand what I've done wrong, but apparently it's pretty brutal considering how everyone seems to be having their bot running fine. Maybe I have the wrong version of something installed? If it's some other dependency I need or something else I need to update, I have no idea how to do that. Would appreciate useful tips on that if that's the case. Perhaps my Path isn't configured correctly? I don't know.

Through this link, you may find my Pastebin containing the contents of my recent most [npm-debug.log](http://pastebin.com/tdwGNjMm) file. Any additional information you all may require that I can provide I will be more than happy to share.

Thanks a bunch for giving me some of your time.

**Comment by Einarin** [comment]
Sorry nobody responded to this earlier. From a look at your pastebin, my guess might be that this wasn't in a visual studio command prompt. I just brought the bot up to date with current libraries, and removed the dependency on libxmljs, so this exact problem won't happen any more. If you're still interested and have problems, feel free to comment here and I'll try to help more.
