### ISSUE TITLE
StreamIntent error, "Super expression must either be null or a function, not an object"

### ISSUE THREAD

**Issue by Burgy123123** [chalda/DiscordBot#71]
<img src="http://image.prntscr.com/image/a558eb858f534f2d89f7a1c593a00c12.png">
This is after a fresh npm install on a new server. I don't understand how to fix the error if someone could shed some light on it.

**Comment by Einarin** [comment]
Looks like you're running an old version of node. We require Node 6.0 or greater because that's what Discord.js requires.
