### ISSUE TITLE
Using a token in auth.json?

### ISSUE THREAD

**Issue by Canaduhh** [chalda/DiscordBot#77]
For my bot, I have an application with a token instead of a bot user account. However, I cannot figure out how to get the auth.json to use a token instead of a username/password. Every way I've tried has resulted in the console saying

`bot.loginWithToken is not a function.`

Any help on this would be appreciated.

**Comment by HaremK1ng** [comment]
Replace username and password with: `"bot_token": "Your token",`

**Comment by DerfOh** [comment]
Make sure to remove or comment out the email/password section. Your token can be generated following this guide if you're not sure: https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token

**Comment by Einarin** [comment]
Discord.js unified the login function. We were using an old version of the API, and everything was broken. Should all be good now. You may need #82
