### ISSUE TITLE
[error] @102787683822080000 went @102787683822080000RN DiscordBot@0.1.1 license should be a valid SPDX license expression

### ISSUE THREAD

**Issue by Nerdietony** [chalda/DiscordBot#79]
I get this error

D:\gem\gem>node discord_bot2.js
logging in with token
<@81315195011469312> went <@81315195011469312>
<@114899955575029765> went <@114899955575029765>
Ready to begin! Serving in 45 channels
logging in with token
Loaded 39 chat commands type !help in Discord for a commands list.
<@148931616452902912> went <@148931616452902912>
<@81660953434796032> went <@81660953434796032>
<@109206406984404992> went <@109206406984404992>
<@80801429802983424> went <@80801429802983424>
Disconnected!

**Comment by Nerdietony** [comment]
nvm, i get this error now

<@155077796413046784> went <@155077796413046784>
<@102787683822080000> went <@102787683822080000>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@102787683822080000> went <@102787683822080000>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@118965279563841536> went <@118965279563841536>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@118965279563841536> went <@118965279563841536>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@120353989886869504> went <@120353989886869504>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@120353989886869504> went <@120353989886869504>
<@104979509589106688> went <@104979509589106688>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@104979509589106688> went <@104979509589106688>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@121213299055525888> went <@121213299055525888>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@121213299055525888> went <@121213299055525888>
<@176365165032243201> went <@176365165032243201>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@176365165032243201> went <@176365165032243201>
<@135721874591186944> went <@135721874591186944>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@135721874591186944> went <@135721874591186944>
<@92799852278194176> went <@92799852278194176>
<@92799852278194176> went <@92799852278194176>WARN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@84938373847859200> went <@84938373847859200>WARN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@84938373847859200> went <@84938373847859200>
<@88608197891346432> went <@88608197891346432>WARN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@88608197891346432> went <@88608197891346432>WARN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@109821286888296448> went <@109821286888296448>
<@127917288459337728> went <@127917288459337728>
<@109821286888296448> went <@109821286888296448>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@127917288459337728> went <@127917288459337728>
<@208869516199854080> went <@208869516199854080>
<@208869516199854080> went <@208869516199854080>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@152263518043897856> went <@152263518043897856>
<@152263518043897856> went <@152263518043897856>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@186373210495909889> went <@186373210495909889>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@186373210495909889> went <@186373210495909889>
<@88608197891346432> went <@88608197891346432>WARN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@88608197891346432> went <@88608197891346432>WARN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@116924228804149256> went <@116924228804149256>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@116924228804149256> went <@116924228804149256>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@105554858173591552> went <@105554858173591552>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@105554858173591552> went <@105554858173591552>
<@133950904226414593> went <@133950904226414593>RN DiscordBot@0.1.1 license should be a valid SPDX license expression
<@114550759378386952> went <@114550759378386952>
<@133950904226414593> went <@133950904226414593>RN DiscordBot@0.1.1 license should be a valid SPDX license expression

**Comment by nmynarcik** [comment]
I was getting this too. Im also not experiencing the bot replying back to commands.

**Comment by Nerdietony** [comment]
Same.

**Comment by eslachance** [comment]
`GNU` is not a valid SPDX license expression. That's the issue. Take a look at https://spdx.org/licenses/ for a list of valid SPDX license expressions. (the "Identifier" column I believe).

**Comment by Nerdietony** [comment]
So replace ```gnu``` to ```GPL-3.0``` in ```auth.json```??

**Comment by Nerdietony** [comment]
I mean, will that do the trick?

**Comment by chalda** [comment]
Would be in package.json. I'll push a fix in a second

**Comment by Nerdietony** [comment]
OK c:

**Comment by Einarin** [comment]
Fixed by ff57a20f83e6e3723f7865da9ed94306cfafb529
