### ISSUE TITLE
wheres the auth.json file

### ISSUE THREAD

**Issue by KDiaCoding** [chalda/DiscordBot#83]
sorry if this is a really nooby question but wheres the auth.json file and where can I find it?

**Comment by Einarin** [comment]
You have to create it. The repo includes an auth.json.example file you can use as a guide. It contains the credentials for the various services the bot can use, including Discord itself.

**Comment by KDiaCoding** [comment]
so I just rename the example to auth.json and I add the things I want and
that's it?
do I need to add any other text or commands?(I'm a noob)

**Comment by KDiaCoding** [comment]
and btw how do I run it(sorry I'm such a noob)
