### ISSUE TITLE
Twitch command broken

### ISSUE THREAD

**Issue by Einarin** [chalda/DiscordBot#90]
Twitch add application id requirements to their API. This broke our twitch command, which was using anonymous access.

Should be easy to fix, just need to add support for having a twitch client id in auth.json and modify the command to use it. See https://dev.twitch.tv/docs#client-id for details on the api side.

**Comment by zachwright** [comment]
Looks like you patched this already, @Einarin in commit fe21233302e9284b3024b1ccee9d6397a0693938. Does that sound right?

**Comment by Einarin** [comment]
I think I did, but then it got broken again. I fixed it again.
