### ISSUE TITLE
Cleverbot Plugin Broken

### ISSUE THREAD

**Issue by Einarin** [chalda/DiscordBot#93]
The talk command, which uses Cleverbot, presently just returns `<html>` to all queries

**Comment by Einarin** [comment]
This is inconsistent. It seems to only be broken for some people?

**Comment by sr229** [comment]
Cleverbot has been broken on more people. I recommend the usage of Cleverbot.io Instead.

**Comment by Einarin** [comment]
I removed the existing cleverbot plugin since it doesn't work as is. Can implement a new one if someone wants to.
