### ISSUE TITLE
Problem installing the packages

### ISSUE THREAD

**Issue by ryandomasta** [chalda/DiscordBot#94]
Valeries-iMac:DiscordBot-master Ryan$ npm install
npm WARN engine discord.js@9.3.1: wanted: {"node":">=6.0.0"} (current: {"node":"4.5.0","npm":"2.15.9"})
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN engine punycode@2.0.1: wanted: {"node":">=6"} (current: {"node":"4.5.0","npm":"2.15.9"})
-
> ref@1.3.3 install /Users/Ryan/Desktop/DiscordBot/DiscordBot-master/node_modules/discord.js/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/binding.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Ryan/Desktop/DiscordBot/DiscordBot-master/node_modules/discord.js/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional dep failed, continuing node-opus@0.2.4

**Comment by Einarin** [comment]
We require Node 6.0. You're using Node 4.5, which is too old.

**Comment by ryandomasta** [comment]
Oh.
