### ISSUE TITLE
ReferenceError: alias is not defined

### ISSUE THREAD

**Issue by cikez** [chalda/DiscordBot#96]
Hello. Thank you for this cool bot but I am having a bit of an issues. Anytime I type !help or any other command in the chat I get the error:

Line 768
alias = aliases[cmdTxt];
ReferenceError: alias is not defined.

Please help!
![capture](https://cloud.githubusercontent.com/assets/5069449/21479386/eeda0322-cb21-11e6-9b8d-12f3169853c0.PNG)

**Comment by AdrseinGames** [comment]
delate evry thing the retry. its beascause node_modules/ws/lib/WebSocket.js
and  node_modules/discord.js/src/client/
try to delate node_modules and do npm install in home/kyle/Desktop/SMBot

**Comment by cikez** [comment]
@AdrseinGames Thank you! That worked. Sorry, I am still somewhat new to node. Thanks again.
